<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\DetailClassDepartment;

class DetailClassDepartmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DetailClassDepartment::create([
            'class_user_id'=>1,
            'department_id'=>1
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>1,
            'department_id'=>2
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>1,
            'department_id'=>3
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>1,
            'department_id'=>4
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>1,
            'department_id'=>5
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>1,
            'department_id'=>6
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>1,
            'department_id'=>7
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>1,
            'department_id'=>8
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>1,
            'department_id'=>9
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>1,
            'department_id'=>10
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>1,
            'department_id'=>11
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>1,
            'department_id'=>12
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>1,
            'department_id'=>13
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>1,
            'department_id'=>14
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>1,
            'department_id'=>15
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>1,
            'department_id'=>16
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>1,
            'department_id'=>17
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>1,
            'department_id'=>18
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>1,
            'department_id'=>19
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>1,
            'department_id'=>20
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>1,
            'department_id'=>21
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>2,
            'department_id'=>1
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>2,
            'department_id'=>2
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>2,
            'department_id'=>3
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>2,
            'department_id'=>4
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>2,
            'department_id'=>5
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>2,
            'department_id'=>6
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>2,
            'department_id'=>7
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>2,
            'department_id'=>8
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>2,
            'department_id'=>9
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>2,
            'department_id'=>10
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>2,
            'department_id'=>11
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>2,
            'department_id'=>12
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>2,
            'department_id'=>13
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>2,
            'department_id'=>14
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>2,
            'department_id'=>15
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>2,
            'department_id'=>16
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>2,
            'department_id'=>17
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>2,
            'department_id'=>18
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>2,
            'department_id'=>19
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>2,
            'department_id'=>20
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>2,
            'department_id'=>21
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>3,
            'department_id'=>1
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>3,
            'department_id'=>2
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>3,
            'department_id'=>3
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>3,
            'department_id'=>4
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>3,
            'department_id'=>5
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>3,
            'department_id'=>6
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>3,
            'department_id'=>7
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>3,
            'department_id'=>8
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>3,
            'department_id'=>9
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>3,
            'department_id'=>10
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>3,
            'department_id'=>11
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>3,
            'department_id'=>12
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>3,
            'department_id'=>13
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>3,
            'department_id'=>14
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>3,
            'department_id'=>15
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>3,
            'department_id'=>16
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>3,
            'department_id'=>17
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>3,
            'department_id'=>18
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>3,
            'department_id'=>19
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>3,
            'department_id'=>20
        ]);
        DetailClassDepartment::create([
            'class_user_id'=>3,
            'department_id'=>21
        ]);

    }
}
